### PR TITLE
match breakpoints to official breakpoints

### LINKED ISSUE #1027: Responsive breakpoints are not consistent with "officials" breakpoints
**Describe the bug**
For some components, responsive breakpoints are not in sync with officials breakpoints. For instance in the file `https://github.com/BuilderIO/builder/blob/main/packages/react/src/blocks/Columns.tsx` the column will be stacked at 999px if we choose tablet. It should be 991px.

It causes weird problems between 991 and 999px.

There might be others files affected.

**To Reproduce**
Create a Column components and set up Column to stack on Tablet. When inspecting the css on the column component you can see the problematic media query .

**Expected behavior**
Builder.io responsive breakpoints should be : 
- Mobile: 0-639px
- Tablet: 640px-991px
- Desktop: 992px+

according to : https://forum.builder.io/t/builder-io-breakpoints/321

**Screenshots**
image

**Additional context**
On React, not tested for other frameworks.

### PR DESCRIPTION
**Pull request by charkour**
## Description

Fixes #1027

**Describe the bug**
As reported, some default Builder components' responsive breakpoints are not in sync with officials breakpoints. This includes Block, Image, and Column. Their large breakpoints are 999px when they should be 991px according to @steve8708 on the [Builder forms](https://forum.builder.io/t/builder-io-breakpoints/321). 

This causes problems between 991px and 999px. 

**To Reproduce**
Create a Column component and switch to the Tablet View. You can now see the breakpoint is set to 999px and not 991px. 

image

**Expected behavior**
Builder Component responsive breakpoints should be:

- Mobile: 0-639px
- Tablet: 640px-991px
- Desktop: 992px+

### CODE REVIEW

**Review by mrkoreye — APPROVED** [review]
thank you for sending this fix @charkour!

**Comment by charkour** [comment]
Great, thank you! Please make any necessary changes. You know much more about the system than I do. This is my "best effort"

File: examples/react-design-system/src/pages/HomepageFullHeadless.jsx [hunk 1]
```diff
@@ -480,7 +480,7 @@ const Div24 = styled.div`
   line-height: normal;
   width: calc(33.333333333333336% - 13.333333333333334px);
   margin-left: 20px;
-  @media (max-width: 999px) {
+  @media (max-width: 991px) {
```
Comment (charkour) [inline examples/react-design-system/src/pages/HomepageFullHeadless.jsx:483]: @mrkoreye, I'll leave this change up to your discretion. It seemed, based on the context, that this example was anticipating the large breakpoint to be 999px so I made the assumption to change it to 991px.

File: packages/email/src/components/Block.tsx [hunk 2]
```diff
@@ -24,7 +24,7 @@ const sizes = {
   medium: {
     min: 640,
     default: 641,
-    max: 999,
+    max: 991,
```
Comment (charkour) [inline packages/email/src/components/Block.tsx:27]: Also, I made this change but was unaware of what the `email` package is. Perhaps this is an incorrect change.

**Comment by charkour** [comment]
Thanks for getting this merged in, @mhevery. 

What is your typical standard for cutting a new release? Thanks!

**Comment by charkour** [comment]
I made an internal patch for the interim.
